<?php
require_once __DIR__ . '/../../includes/authSession.php';
require_once __DIR__ . '/../includes/passwordVerification.php';
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <title>Notification | E-Recycle</title>
  <link rel="stylesheet" href="\capstoneweb/assets/fontawesome-free-7.0.1-web/css/all.min.css">
  <link rel="stylesheet" href="\capstoneweb/assets/bootstrap-5.3.7-dist/css/bootstrap.css" />
  <link rel="stylesheet" href="\capstoneweb/assets/bootstrap-icons-1.13.1/bootstrap-icons.css">
  <link rel="icon" type="image/x-icon" href="/capstoneweb/assets/E-Recycle_Logo_with_Green_and_Blue_Palette-removebg-preview.png"> 
  <link rel="stylesheet" href="\capstoneweb/user-admin.css">
  <link rel="stylesheet" href="\capstoneweb/user-admin1.css">
</head>
<style>
.qr-card {
  background: #fff;
  max-width: 500px;
  width: 100%;
  border-radius: 15px;
  border: 1px solid #dee2e6;
}

.qr-logo {
  width: 60px;
  height: 60px;
  object-fit: contain;
}

.qr-image {
  width: 220px;
  border: 2px solid #198754;
  border-radius: 10px;
  padding: 10px;
  background: #f8f9fa;
}

.qr-header h3 {
  font-size: 1.25rem;
}

.qr-info p {
  margin-bottom: 6px;
  font-size: 0.95rem;
}

.qr-card a {
  color: #0d6efd;
  text-decoration: none;
}
.qr-card a:hover {
  text-decoration: underline;
}
</style>


<body>

  <!-- Sidebar -->
  <?php include '../includes/sidebar.php'; ?>

  <!-- Sidebar Toggle Button (visible on all screens) -->
  <button id="toggleSidebar"><i class="fa fa-bars"></i></button>

  <!-- Overlay (for mobile view) -->
  <div class="overlay"></div>

  <!-- Content -->
  <div class="content" id="content">
    <header class="dashboard-header">
      <div class="header-left">
        <img src="\capstoneweb/assets/logo_matimbubong.jpeg" alt="E-Recycle Logo" class="header-logo">
        <div class="header-text">
          <h1>E-Recycle Notification Page</h1>
          <p>Municipality of San Ildefonso</p>
        </div>
      </div>

      <div class="header-right">
        <span class="date-display"><?php echo date("F j, Y"); ?></span>
      </div>
    </header>

    <!-- qr code-->
    <div class="container mt-4 d-flex justify-content-center align-items-center">
  <div class="qr-card shadow p-4 rounded text-center">
    <div class="qr-header mb-3">
      <div class="d-flex justify-content-between align-items-center mb-3">
        <img src="/capstoneweb/assets/logo_matimbubong.jpeg" alt="Left Logo" class="qr-logo">
        <h3 class="fw-bold text-success">E-Recycle QR Certificate</h3>
        <img src="/capstoneweb/assets/E-Recycle_Logo_with_Green_and_Blue_Palette-removebg-preview.png" alt="Right Logo" class="qr-logo">
      </div>
      <p class="text-muted mb-0">Municipality of San Ildefonso</p>
    </div>

    <?php
    $user_id = $_SESSION['userid'];
    $qrQuery = "SELECT userName, email, purok, qr_code FROM account WHERE userid = ?";
    $stmt = $conn->prepare($qrQuery);
    $stmt->bind_param("i", $user_id);
    $stmt->execute();
    $result = $stmt->get_result();

    if ($result && $row = $result->fetch_assoc()) {
        $qrFile = trim($row['qr_code']);
        $absolutePath = __DIR__ . "/../../uploads/qrcodes/" . $qrFile;
        $webPath = "/capstoneweb/uploads/qrcodes/" . $qrFile;

        if (!empty($qrFile) && file_exists($absolutePath)) {
            echo "<div class='qr-display'>";
            echo "<img src='" . htmlspecialchars($webPath) . "' alt='Your QR Code' class='qr-image'>";
            echo "</div>";
            
            echo "<div class='qr-info mt-3 text-start mx-auto' style='max-width: 320px;'>";
            echo "<p><strong>Full Name:</strong> " . htmlspecialchars($row['userName']) . "</p>";
            echo "<p><strong>Email:</strong> " . htmlspecialchars($row['email']) . "</p>";
            echo "<p><strong>Purok:</strong> " . htmlspecialchars($row['purok']) . "</p>";
            echo "<p><strong>Role:</strong> " . htmlspecialchars($_SESSION['role']) . "</p>";
            echo "<p><strong>Date Issued:</strong> " . date('F d, Y') . "</p>";
            echo "</div>";

            echo "<p class='text-muted small mt-3'>This is a secure QR code generated by E-Recycle and can be verified at <a href='#'>erecycle.gov.ph</a></p>";
        } else {
            echo "<div class='alert alert-warning'>QR code not found. Please contact the administrator.</div>";
        }
    } else {
        echo "<div class='alert alert-danger'>Failed to load QR code data.</div>";
    }
    ?>
  </div>
</div>

  </div>

  <!-- Verify Password Modal -->
  <div class="modal fade" id="verifyPasswordModal" tabindex="-1" aria-labelledby="verifyPasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form method="post" action="">
          <div class="modal-header">
            <h5 class="modal-title" id="verifyPasswordModalLabel">Verify Your Password</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="mb-3">
              <label for="verifyPassword" class="form-label">Enter Password</label>
              <input type="password" class="form-control" name="verify_password" id="verifyPassword" required>
            </div>
          </div>
          <div class="modal-footer">
            <button type="submit" name="verify_submit" class="btn btn-primary">Verify</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- toggle -->
  <script src="../../assets/sidebarToggle.js"></script>

</body>
</html>
